[build]
  command = "cd front && npm install && ng build --configuration production"
  publish = "front/dist/front"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
